name: test-tutorial-workflow

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
    inputs:
      rose_ref:
        description: The Rose branch to test against
        required: false
      cylc_ref:
        description: The Cylc branch to test against
        required: false
      cylc_rose_ref:
        description: The Cylc branch to test against
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: configure python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: checkout cylc-doc
        uses: actions/checkout@v2

      - name: install dependencies
        uses: ./.github/actions/install-dependencies

      - name: install cylc-doc
        run: pip install .[tutorial]

      - name: install libs
        env:
          cylc_ref: ${{ github.event.inputs.cylc_ref || 'master' }}
          rose_ref: ${{ github.event.inputs.rose_ref || 'master' }}
          cylc_rose_ref: ${{ github.event.inputs.cylc_rose_ref || 'master' }}
        run: |
          pip install  \
            "cylc-flow @ git+https://github.com/cylc/cylc-flow@${cylc_ref}" \
            "cylc-rose @ git+https://github.com/cylc/cylc-rose@${cylc_rose_ref}"
          git clone --depth 1 -b "${meto_rose}" https://github.com/metomi/rose ../rose
          pip install -e ../rose[all]

      - name: run tutorial workflow
        run: |
          mkdir -p "${HOME}/cylc-run"
          bin/run-validate

      - name: debug
        if: failure()
        run: |
          find ~/cylc-run -name job.err -exec cat {} +  # cylc error files
